### ISSUE TITLE
better interaction on Desktop of Bottom Sheet 

### ISSUE THREAD

**Issue by lyricat** [fox-one/uikit#24]
on Desktop, the bottom sheet need a different appearance and behavior than on Mobile. 

the dropdown style is better on Desktop.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/67439/117591856-3f847c00-b171-11eb-9cbb-dbb2e800771b.png">

**Comment by divisey** [comment]
updated in v2.0.58
